apiVersion: apps/v1
kind: Deployment
metadata:
  name: bash-ingress
  labels:
    app: bash-ingress
spec:
  selector:
    matchLabels:
      app: bash-ingress
  template:
    metadata:
      labels:
        app: bash-ingress
    spec:
      serviceAccountName: bash-ingress
      containers:
        - name: c1
          image: learnk8s/bash-ingress:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bash-ingress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bash-ingress
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bash-ingress
subjects:
  - kind: ServiceAccount
    name: bash-ingress
roleRef:
  kind: Role
  name: bash-ingress
---
apiVersion: v1
kind: Service
metadata:
  name: bash-ingress
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000
  selector:
    app: bash-ingress
